const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const root = path.resolve(__dirname, '..');
global.window = global;
['systems/GameConstants.js','activities.js','systems/PythonSubsetParser.js','systems/CodeBudgetValidator.js'].forEach((file) => require(path.join(root, file)));
const run = spawnSync(process.execPath, ['tests/run-tests.cjs'], { cwd: root, encoding: 'utf8' });
if (run.status !== 0) { process.stderr.write(run.stderr || run.stdout); process.exit(run.status || 1); }
const results = JSON.parse(run.stdout); const byActivity = new Map();
for (const item of results.officialSolutions) { const items = byActivity.get(item.activity) || []; items.push(item); byActivity.set(item.activity, items); }
function structures (activity) { const analysis = window.PythonSubsetParser.parse(activity.officialSolution).analysis; return [...analysis.concepts].sort().concat([...analysis.commands].sort().map((item) => `${item}()`)).join(', '); }
function caseDescription (item) { const input = item.inputs && item.inputs.length ? `; entradas ${item.inputs.join(', ')}` : ''; return `${item.label}${input}: ${item.cause}`; }
function gabarito () {
    const out = ['GABARITO FINAL — PYTON KNIGHT — 20 ATIVIDADES','Versão consolidada em 24 de agosto de 2026','', 'As soluções oficiais abaixo foram executadas pelo mesmo parser, interpretador e mundo físico do jogo. Soluções alternativas são aceitas quando cumprem conceitos, orçamento, interações contextuais e objetivos.',''];
    for (const activity of window.ACTIVITIES) {
        const cases = byActivity.get(activity.id) || [];
        out.push(`ATIVIDADE ${String(activity.id).padStart(2,'0')} — ${activity.nome}`, `Unidade: ${activity.unidade}`, `Conceito: ${activity.concept}`, `Orientação inicial: ${activity.initialFacing}`, `Mecânicas: ${activity.mechanics.join(', ')}`, `Estruturas obrigatórias/empregadas: ${structures(activity)}`, `Orçamento: ${activity.instructionBudget ? `${activity.instructionBudget} instruções semânticas` : 'não aplicável'}`);
        if (activity.mapDesign) out.push(`Mapa reelaborado: ${activity.mapDesign.dimensions}; ${activity.mapDesign.structure}; ${activity.mapDesign.areas} áreas e aproximadamente ${activity.mapDesign.curves} curvas.`);
        out.push('Objetivos:'); activity.objectives.forEach((objective, index) => out.push(`  ${index + 1}. ${objective.label}`));
        out.push('Solução oficial:', ...activity.officialSolution.split('\n').map((line) => `    ${line}`), `Explicação: ${activity.solutionExplanation}`, `Casos executados: ${cases.map(caseDescription).join(' | ')}.`, `Observações de teste: SUCCESS em ${cases.length} cenário(s)/variante(s); matriz funcional de 15 verificações aprovada; segunda execução com reset e código preservado; replay sem duplicação de XP/moedas${activity.id >= 6 ? '; matriz de mapa com 14 verificações aprovada' : ''}${activity.tutorial ? '; tutorial validado etapa por etapa' : ''}.`, '');
    }
    out.push('BALANCEAMENTO PROVISÓRIO','XP, multiplicadores, moedas e guardas ficam em systems/GameConstants.js; orçamentos ficam em activities.js. Reavaliar após playtests.','');
    return out.join('\n');
}
const mechanicName = { M01:'Placa de Pressão',M02:'Placa Alternadora',M03:'Alavanca',M05:'Porta Simples',M06:'Porta Condicional',M07:'Ponte Retrátil',M08:'Ponte Segmentada',M09:'Espinhos',M12:'Armadilha Cíclica',M14:'Espelhos Coloridos',M17:'Pedestal',M18:'Runa de Saída',M19:'Cofre Rúnico',M20:'Guardião',M21:'Chave',M22:'Baú',M23:'Busca em Baús',M24:'Moeda/Rubi',M26:'Totem',M30:'Sensores' };
function testReport () {
    const matrixChecks = results.activityMatrix.length * results.requiredChecksPerActivity; const mapChecks = results.mapDesignMatrix.length * results.mapDesignChecksPerActivity;
    const out = ['# Relatório de Testes — Pyton Knight','', 'Data: 24 de agosto de 2026  ', `Resultado lógico automatizado: **${results.status}**`, '', '## 1. Escopo', '', `- 20 atividades e ${results.officialSolutions.length} cenários oficiais/variantes com SUCCESS.`, `- Matriz funcional: 20 × ${results.requiredChecksPerActivity} = ${matrixChecks} verificações com PASS.`, `- Matriz específica de mapas: 15 × ${results.mapDesignChecksPerActivity} = ${mapChecks} verificações com PASS.`, `- ${results.officialSolutions.length} segundas execuções com reset, código preservado e recompensa idempotente.`, '- Tutoriais 1, 6, 11 e 16 executados etapa por etapa.', `- ${Object.keys(results.regressionChecks).length} regressões globais.`, '- Sintaxe de todos os JavaScripts autorais, cinco assets e referências de `index.html` verificadas.', '', '## 2. Matriz funcional obrigatória por atividade','', '| Atividade | Correta | Incompleta / parada | Sintaxe / comando | Reset / nova execução / código | Parede | Perigo / vidas | Conceito futuro | Objetivo | Recompensa / duplicação | Status |','|---:|---|---|---|---|---|---|---|---|---|---|'];
    for (const item of results.activityMatrix) out.push(`| ${item.activity} | ${item.correct} | ${item.incomplete} | ${item.syntaxError} / ${item.unknownCommand} | ${item.reset} / ${item.rerun} / ${item.codePreserved} | ${item.wallCollision} | ${item.lethalHazard} / ${item.lifeLoss} | ${item.futureConceptBlocked} | ${item.pedagogicalObjective} | ${item.reward} / ${item.noDuplication} | ${item.status} |`);
    out.push('', '## 3. Matriz específica dos mapas 6–20','', '| Ativ. | Dimensão | Início / cristal | Entidades / paredes | Conectividade | Giros / sensores | Contexto | Rota / reset | Perigo / objetivos | Sem atalho | Status |','|---:|---|---|---|---|---|---|---|---|---|---|');
    for (const item of results.mapDesignMatrix) out.push(`| ${item.activity} | ${item.dimensions} | ${item.start} / ${item.crystalReachable} | ${item.entities} / ${item.noEntityInWall} | ${item.connectivity} | ${item.turns} / ${item.sensors} | ${item.contextualInteraction} | ${item.officialRoute} / ${item.reset} | ${item.dangers} / ${item.objectives} | ${item.noPedagogicalShortcut} | ${item.status} |`);
    out.push('', 'A conectividade considera os enlaces espaciais de espelhos e portais. A interação contextual testa explicitamente a rejeição de comandos remotos e o sucesso do mesmo comando junto à entidade.', '', '## 4. Mecânicas e orçamento','', '| Atividade | Mecânicas verificadas | Solução / limite | Orçamento |','|---:|---|---:|---|');
    for (const activity of window.ACTIVITIES) {
        const analysis = window.PythonSubsetParser.parse(activity.officialSolution).analysis; const special = activity.mechanics.filter((code) => Number(code.slice(1)) <= 30).map((code) => `${code} ${mechanicName[code] || ''}`.trim()).join(', ') || 'M31'; const matrix = results.activityMatrix.find((item) => item.activity === activity.id);
        out.push(`| ${activity.id} | ${special} — PASS | ${activity.instructionBudget ? `${analysis.instructionCount}/${activity.instructionBudget}` : 'N/A'} | ${matrix.budget} |`);
    }
    const labels = { incompleteExecution:'Código incompleto → INCOMPLETE_EXECUTION',wallCollision:'Parede sem perda de vida',closedDoorBlock:'Porta fechada sem perda de vida',hazardLifeLoss:'Perigo remove uma vida',codePreservedAfterDeath:'Código preservado após morte',unknownCommand:'Comando desconhecido',lockedConcept:'Conceito futuro bloqueado',loopGuard:'Loop infinito interrompido',syntaxError:'Erro de sintaxe',semanticTypeError:'Erro semântico de tipos',semanticBudgetCount:'Ponto e vírgula contado',indexAssets:'Scripts e cinco assets presentes',noAbsoluteMovementApi:'Sem movimento absoluto',noDynamicCodeExecution:'Sem eval/new Function',budgetExceededNoLifeLoss:'Orçamento sem perda de vida',deterministicRerun:'Reexecução determinística',guidedTutorials:'Tutoriais completos',rewardIdempotency:'Recompensas idempotentes',xpMonotonicity:'XP proporcional às vidas',contextualInteractions:'Interações exigem contexto espacial',orientedSensors:'Sensores respeitam orientação',redesignedMapGeometry:'Geometria 6–20 validada',devModeNavigation:'Navegação ?dev=1 preservada' };
    out.push('', '## 5. Regressões globais','', '| Verificação | Resultado |','|---|---|'); for (const [key,value] of Object.entries(results.regressionChecks)) out.push(`| ${labels[key] || key} | ${value} |`);
    out.push('', '## 6. Reprodução','', '```bash','node tests/run-tests.cjs','for f in Boot.js Game.js MainMenu.js Preloader.js activities.js systems/*.js ui/*.js tests/run-tests.cjs tools/*.cjs; do node --check "$f" || exit 1; done','```','', '## 7. Critério de aprovação','', 'Nenhuma atividade recebeu PASS apenas porque o parser aceitou o código. Cada caso oficial precisou navegar pelo mapa, alterar os mecanismos corretos, cumprir todos os objetivos e retornar `SUCCESS`. A suíte também verifica geometria, alcance, contexto de interação, sensores orientados, reset e proteção do conceito pedagógico.','', '## 8. Homologação visual','', 'Os mapas usam escala dinâmica entre 68 px e 35 px por tile para caber na área de dungeon; o maior mapa mede 20 × 14. A inspeção visual final em navegador real deve continuar fazendo parte do playtest de arte e legibilidade, sem bloquear a aprovação lógica registrada aqui.','');
    return out.join('\n');
}
function entitySummary (activity) {
    const grouped = new Map();
    for (const entity of activity.entities || []) { const list = grouped.get(entity.type) || []; list.push(`${entity.id} (${entity.row},${entity.column})`); grouped.set(entity.type, list); }
    return [...grouped.entries()].map(([type, items]) => `  - ${type}: ${items.join(', ')}`).join('\n');
}
function mapReport () {
    const out = ['# Relatório de Reelaboração dos Mapas — Atividades 6 a 20','', 'Data: 24 de agosto de 2026  ', 'Status geral: **PASS — mapas implementados e rotas oficiais executadas fisicamente**', '', '## Escopo e decisões','', '- Os objetivos pedagógicos e os sistemas globais existentes foram preservados.', '- `PythonSubsetParser`, `CommandInterpreter`, vidas, XP, moedas, persistência, Livro Mágico, progressão e validador de orçamento não foram refeitos.', '- A adaptação indispensável ficou restrita à espacialização das interações, sensores orientados, teletransporte com orientação e representação visual de regiões/entidades.', '- Os mapas cabem na área atual por escala dinâmica: 68 px/tile nos menores e 35 px/tile no mapa 20 × 14; não foi necessária reforma de câmera nem redução ilegível.', '- O modo `?dev=1` permanece usando o fluxo existente e libera ANTERIOR/PRÓXIMA sem alterar o bloqueio normal.', '', '## Resumo','', '| Ativ. | Dimensão | Áreas | Curvas aprox. | Estrutura | Status |','|---:|---|---:|---:|---|---|'];
    for (const activity of window.ACTIVITIES.slice(5)) out.push(`| ${activity.id} | ${activity.mapDesign.dimensions} | ${activity.mapDesign.areas} | ${activity.mapDesign.curves} | ${activity.mapDesign.structure} | PASS |`);
    out.push('', '## Detalhamento por atividade','');
    for (const activity of window.ACTIVITIES.slice(5)) {
        const mapTest = results.mapDesignMatrix.find((item) => item.activity === activity.id); const cases = byActivity.get(activity.id) || [];
        out.push(`### Atividade ${activity.id} — ${activity.nome}`,'', `- Dimensão final: **${activity.mapDesign.dimensions}**.`, `- Estrutura espacial: ${activity.mapDesign.structure}.`, `- Áreas e curvas: ${activity.mapDesign.areas} áreas; aproximadamente ${activity.mapDesign.curves} mudanças de direção/curvas.`, '- Mecânicas posicionadas:', entitySummary(activity), `- Mudança na solução oficial: ${activity.solutionExplanation}`, `- Testes: ${cases.length} rota(s)/variante(s) com SUCCESS; dimensão, início, cristal, entidades, paredes, conectividade, giros, sensores, contexto, reset, perigos, objetivos, execução incompleta e proteção contra atalho com ${mapTest.status}.`, '- Status: **PASS**.', '');
    }
    out.push('## Interações espacializadas','', '- `input()` e `print()` contextuais quando a atividade usa pedestal/runa.', '- `ativar_alavanca()` exige proximidade; `abrir_porta()` exige proximidade do bloqueio.', '- `entrar_espelho()` e `entrar_portao()` exigem que Guto esteja no tile da entidade e preservam orientação de destino.', '- `coletar_rubi()` exige o tile do rubi nas atividades de coleta manual.', '- `abrir_bau()` e `desativar_armadilha()` operam no objeto à frente.', '- `tem_bau_a_frente()`, `tem_armadilha_a_frente()`, `tem_placa_a_frente()` e `corredor_continua()` respeitam a orientação.', '', '## Resultado dos testes','', `- ${results.officialSolutions.length} casos oficiais/replays: PASS.`, `- ${results.activityMatrix.length * results.requiredChecksPerActivity} verificações funcionais: PASS.`, `- ${results.mapDesignMatrix.length * results.mapDesignChecksPerActivity} verificações específicas de mapa: PASS.`, `- ${Object.keys(results.regressionChecks).length} regressões globais: PASS.`, '');
    return out.join('\n');
}
fs.mkdirSync(path.join(root,'build'), { recursive:true });
fs.writeFileSync(path.join(root,'Gabarito_Final_Pyton_Knight_20_Atividades.txt'), gabarito());
fs.writeFileSync(path.join(root,'RELATORIO_DE_TESTES_PYTON_KNIGHT.md'), testReport());
fs.writeFileSync(path.join(root,'RELATORIO_REELABORACAO_MAPAS.md'), mapReport());
fs.writeFileSync(path.join(root,'build/activity_catalog.json'), JSON.stringify(window.ACTIVITIES,null,2));
fs.writeFileSync(path.join(root,'build/test_results.json'), JSON.stringify(results,null,2));
process.stdout.write(JSON.stringify({status:'PASS',activities:20,officialCases:results.officialSolutions.length,activityChecks:results.activityMatrix.length * results.requiredChecksPerActivity,mapChecks:results.mapDesignMatrix.length * results.mapDesignChecksPerActivity,regressions:Object.keys(results.regressionChecks).length},null,2));
