const test=require('node:test');const assert=require('node:assert/strict');const {setup}=require('./helpers.cjs');
for(const power of [25,15,5,20,10,9])for(const portal of [1,2,3])test(`Atividade 15: poder ${power}, portal ${portal}`,async()=>{
 const {context:c,scene}=setup();const s=scene(c.ACTIVITIES[14]);s.runState.inputs=[String(power)];s.runState.hasKey=true;s.runState.flags.leverDone=true;const e=c.DungeonSystem.getEntity(s,`portal${portal}`);s.gutoPosition={linha:e.row,coluna:e.column};const before=JSON.stringify(s.gutoPosition),wallet=JSON.stringify(s.playerProgress);const expected=power>=20?3:power>=10?2:1;
 if(portal===expected){assert.equal(await c.DungeonSystem.callApi(s,'entrar_portao',[portal],{lineNumber:4}),true);assert.equal(s.runState.flags.correctPortal,true);}
 else{await assert.rejects(async()=>c.DungeonSystem.callApi(s,'entrar_portao',[portal],{lineNumber:4}),/Portão incorreto/);assert.equal(s.runState.flags.correctPortal,false);assert.equal(e.state,'available');assert.equal(JSON.stringify(s.gutoPosition),before);assert.equal(JSON.stringify(s.playerProgress),wallet);assert.equal(s.livesRemaining,3);}
});
for(const power of ['25','15','5'])test(`Solução oficial completa da 15 preservada: ${power}`,async()=>{const h=setup();const r=await h.run(h.context.ACTIVITIES[14],{inputs:[power]});assert.equal(r.result.cause,'SUCCESS');});
for(const [power,forced] of [['25','5'],['15','25'],['5','15']])test(`Programa com classificação forçada incorreta não recompensa: ${power} como ${forced}`,async()=>{const h=setup(),a=h.context.ACTIVITIES[14];const code=a.officialSolution.replace('if poder >= 20:',`poder = ${forced}\nif poder >= 20:`);const s=h.scene(a,{inputs:[power],code});const before=JSON.stringify(s.playerProgress);const r=await h.context.CommandInterpreter.executar(s);assert.notEqual(r.cause,'SUCCESS');assert.equal(s.runState.flags.correctPortal,false);assert.equal(JSON.stringify(s.playerProgress),before);assert.equal(s.livesRemaining,3);assert.match(r.message,/Portão incorreto/);});
test('Conceito e comando em ramo não executado não satisfazem objetivo',async()=>{const h=setup();const a={...h.languageActivity,objectives:[{type:'used_concept',concept:'print',label:'Imprima'},{type:'used_command',command:'print',label:'Chame print'}]};const r=await h.run(a,{code:'if False:\n    print("oculto")'});assert.equal(r.result.cause,'INCOMPLETE_EXECUTION');assert.ok(r.scene.objectiveStatuses.every(x=>!x.completed));});
test('Loop sem iteração não satisfaz objetivo de repetição',async()=>{const h=setup();const a={...h.languageActivity,objectives:[{type:'used_concept',concept:'for',label:'Repita'}]};const r=await h.run(a,{code:'for i in range(0):\n    x = 1'});assert.equal(r.result.cause,'INCOMPLETE_EXECUTION');});
test('Portal sem input não ativa nem recebe correctPortal',async()=>{const h=setup(),s=h.scene(h.context.ACTIVITIES[14]);const e=h.context.DungeonSystem.getEntity(s,'portal1');s.runState.hasKey=true;s.runState.flags.leverDone=true;s.gutoPosition={linha:e.row,coluna:e.column};await assert.rejects(async()=>h.context.DungeonSystem.callApi(s,'entrar_portao',[1],{lineNumber:1}),/Leia um poder inteiro/);assert.equal(s.runState.flags.correctPortal,false);assert.equal(e.state,'available');});
test('Novas sprites substituem escudos, estante e bandeira nos papéis principais',()=>{const h=setup();h.load('systems/MapRenderer.js');for(const [entity,role] of [[{type:'guardian',id:'guardian'},'custom_guardian'],[{type:'guardian',id:'basilisk'},'custom_basilisk'],[{type:'pedestal'},'custom_pedestal'],[{type:'output_rune'},'custom_rune'],[{type:'totem'},'custom_totem']])assert.equal(h.context.MapRenderer.appearance({...entity,state:'off'}).role,role);assert.equal(h.context.MapRenderer.appearance({type:'gate',id:'cofre',state:'open'}).role,'chest_open_fallback');});
