const test=require('node:test');const assert=require('node:assert/strict');const {fixture}=require('./ui-fixture.cjs');
for(let index=0;index<20;index++)test(`UI/renderer real com adaptadores: atividade ${index+1}, solução, replay e limpeza`,async()=>{
 const {context:c,game,host}=fixture();const s=game(index);assert.equal(s.editorTexto.value,s.atividade.tutorialSteps?.[0].code||s.atividade.codigoInicial||'');assert.ok(s.guto.active);assert.ok(s.entitySprites);
 s.tutorialStepIndex=s.atividade.tutorialSteps?s.atividade.tutorialSteps.length-1:0;s.editorTexto.value=s.atividade.officialSolution;s.testInputQueue=[...(s.atividade.testInputs||[])];const result=await c.CommandInterpreter.executar(s);assert.equal(result.cause,'SUCCESS',JSON.stringify(result));
 assert.equal(host.querySelector('.run').disabled,false);assert.ok(host.querySelector('.next'));assert.equal(s.codeEditor.errorLine,null);const before=JSON.stringify({...s.playerProgress,updatedAt:null});s.testInputQueue=[...(s.atividade.testInputs||[])];await c.CommandInterpreter.executar(s);assert.equal(JSON.stringify({...s.playerProgress,updatedAt:null}),before);s.hooks.shutdown();assert.equal(host.children.length,0);
});
test('Feedback extenso preserva controles e conteúdo como texto (sem medição CSS)',()=>{const {context:c,game,host}=fixture();const s=game(5);const buttons=host.querySelectorAll('.actions button');c.GameUI.definirFeedback(s,'<script>não executar</script>\n'.repeat(1000),'error');assert.equal(host.querySelector('.feedback').children.length,0);assert.deepEqual(host.querySelectorAll('.actions button'),buttons);assert.equal(buttons.length,4);});
test('input mostra pergunta, recebe texto exato, fecha e permite nova entrada',async()=>{const {context:c,game,host}=fixture();const s=game(5);const p=c.GameUI.solicitarEntrada(s,'Qual palavra?');assert.equal(host.querySelector('.input-area').hidden,false);assert.equal(host.querySelector('.input-prompt').textContent,'Qual palavra?');assert.equal(host.querySelector('.runtime-input').focused,true);host.querySelector('.runtime-input').value=' AURORA ';await host.querySelector('.input-area').emit('submit');assert.equal(await p,' AURORA ');assert.equal(host.querySelector('.input-area').hidden,true);const second=c.GameUI.solicitarEntrada(s,'Outra?');c.GameUI.cancelarEntrada(s);await assert.rejects(second,e=>e.cause==='EXECUTION_CANCELLED');});
test('Restaurar durante input cancela execução sem perder vidas',async()=>{const {context:c,game,host}=fixture();const s=game(6);s.editorTexto.value=s.atividade.officialSolution;s.testInputQueue=[];const execution=c.CommandInterpreter.executar(s);for(let i=0;i<50&&!s.cancelInput;i++)await new Promise(r=>setImmediate(r));assert.ok(s.cancelInput);const lives=s.livesRemaining;await host.querySelector('.restore').emit('click');await execution;assert.equal(s.livesRemaining,lives);assert.equal(s.executando,false);assert.equal(host.querySelector('.input-area').hidden,true);assert.equal(s.editorTexto.value,s.atividade.codigoInicial);});
test('Anterior/próxima preservam rascunho e usam fade; fase bloqueada não navega',async()=>{const {context:c,game,host}=fixture();let s=game(5);s.editorTexto.value='# rascunho';await c.GameUI.navegar(s,4);assert.equal(s.transition.data.atividadeIndex,4);s.hooks.shutdown();s=game(5);assert.equal(s.editorTexto.value,'# rascunho');s.devMode=false;s.playerProgress.unlockedMax=1;await c.GameUI.navegar(s,19);assert.equal(s.transition,undefined);});
test('Todos os estados visuais das entidades apontam para texturas catalogadas',()=>{const {context:c}=fixture();for(const a of c.ACTIVITIES)for(const e of a.entities||[])for(const state of ['open','active','on','correct','defeated','answered','closed','inactive','off','incorrect','collected']){const look=c.MapRenderer.appearance({...e,state});assert.ok(c.AssetCatalog[look.role]||c.AssetCatalog.entries?.[look.role],`${e.type}: ${look.role}`);}});
test('Menu mostra progresso e abre a atividade disponível sem perfil',async()=>{const {context:c,host}=fixture();const Menu=c.pytonKnightGame.config.scene[2];const s=new Menu();s.create();assert.equal(host.querySelector('.completed').textContent,'0/20 concluídas');assert.equal(host.querySelector('.xp').textContent,'0 XP');assert.equal(host.querySelector('.coins').textContent,'0 moedas');await host.querySelector('.play-button').emit('click');assert.equal(s.transition.name,'Game');assert.equal(s.transition.data.atividadeIndex,0);s.hooks.shutdown();assert.equal(host.children.length,0);});
