const test=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('./ui-fixture.cjs'),{setupV3}=require('./v3-helpers.cjs');
test('V3 todas as cenas montam mapa, Livro, Diário e controles com dados atuais',()=>{for(let id=1;id<=20;id++){const h=fixture({v3:true}),s=h.game(id-1);assert.equal(s.atividade.id,id);assert.equal(s.atividade.v3,true);assert.ok(s.guto.animation.startsWith('idle_'));assert.ok(s.fog);assert.ok(h.host.querySelector('.journal-toggle'));assert.match(h.host.querySelector('.journal-entries').textContent,/Nenhuma inscrição/);assert.ok(!h.host.textContent.includes('CORAGEM'));assert.ok(!h.host.textContent.includes('AURORA'));}});
test('V3 UI registra somente pista lida, preserva entre execuções e limpa ao REINICIAR',async()=>{
 const h=fixture({v3:true}),s=h.game(6),ui=h.context.GameUI;
 assert.equal(h.host.querySelector('.journal-count').textContent,'0');assert.ok(!h.host.querySelector('.object-identifiers').textContent.includes('memoria'));
 s.editorTexto.value=s.atividade.officialSolution.split('resposta =')[0];await h.context.CommandInterpreter.executar(s);
 assert.equal(h.host.querySelector('.journal-count').textContent,'1');assert.match(h.host.querySelector('.journal-entries').textContent,/CORAGEM/);assert.equal(h.host.querySelector('.clue-dialog').hidden,false);
 await h.host.querySelector('.journal-toggle').emit('click');assert.equal(h.host.querySelector('.journal-panel').hidden,false);
 s.editorTexto.value='andar_frente()';await h.context.CommandInterpreter.executar(s);assert.equal(h.host.querySelector('.journal-count').textContent,'1');
 const pending=ui.solicitarEntrada(s,'Virtude do juramento:');assert.equal(h.host.querySelector('.runtime-input').value,'');assert.equal(h.host.querySelector('.input-data').textContent,'Consulte as pistas encontradas no Diário.');h.host.querySelector('.runtime-input').value='CORAGEM';await h.host.querySelector('.input-area').emit('submit');assert.equal(await pending,'CORAGEM');
 s.livesRemaining=2;await h.host.querySelector('.restore').emit('click');assert.equal(h.host.querySelector('.journal-count').textContent,'0');assert.equal(h.host.querySelector('.clue-dialog').hidden,true);assert.equal(s.livesRemaining,2);assert.equal(Object.keys(s.discoveryState.litRooms).length,0);
});
test('V3 progressão sequencial 1–20, persistência e desbloqueios mantêm valores de recompensa',async()=>{
 const saved=new Map(),localStorage={getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k)};const h=setupV3({localStorage});let xp=0,coins=0;
 for(const a of h.context.ACTIVITIES){const before=h.context.PersistenceService.load();assert.equal(before.unlockedMax,a.id);const {scene:s,result:r}=await h.run(a);assert.equal(r.cause,'SUCCESS');assert.equal(r.reward.firstCompletion,true);xp+=a.rewards?.xpBase||100;coins+=s.runState.coinsPending;assert.equal(s.playerProgress.totalXp,xp);assert.equal(s.playerProgress.walletCoins,coins);assert.equal(s.playerProgress.completedActivities.length,a.id);assert.equal(s.playerProgress.unlockedMax,Math.min(a.id+1,20));}
 const reloaded=setupV3({localStorage}).context.PersistenceService.load();assert.equal(reloaded.totalXp,xp);assert.equal(reloaded.walletCoins,coins);assert.equal(reloaded.completedActivities.length,20);assert.equal(reloaded.unlockedMax,20);
});
for(const lives of [1,2,3])test(`V3 XP com ${lives} vida(s) usa o multiplicador preservado`,async()=>{const h=setupV3(),a=h.context.ACTIVITIES[16],{result:r}=await h.run(a,{lives});assert.equal(r.cause,'SUCCESS');assert.equal(r.reward.xp,Math.round((a.rewards?.xpBase||100)*{1:.5,2:.75,3:1}[lives]));assert.equal(r.reward.coins,5);});
test('V3 orçamento rejeita programas grandes antes de mover ou recompensar',async()=>{for(const id of [4,5,9,10,14,15,19,20]){const h=setupV3(),a=h.context.ACTIVITIES[id-1],{scene:s,result:r}=await h.run(a,{code:Array(a.instructionBudget+1).fill('andar_frente()').join('\n')});assert.equal(r.cause,'CODE_BUDGET_EXCEEDED');assert.deepEqual({...s.gutoPosition},{...a.startPosition});assert.equal(s.playerProgress.totalXp,0);}});
test('V3 segmentos não podem ser ativados ignorando a galeria dos totens',async()=>{for(const id of [16,20]){const h=setupV3(),s=h.scene(h.context.ACTIVITIES[id-1]),bridge=s.runState.entities.find(e=>e.type==='bridge_segment');s.gutoPosition={linha:bridge.row,coluna:bridge.column-1};s.playerFacing='LESTE';await assert.rejects(h.context.DungeonSystem.callApi(s,'ativar_runa',[]),/posição correta/);assert.equal(bridge.state,'inactive');assert.equal(s.runState.flags.runesActivated,undefined);}});
test('V3 baú continua bloqueado enquanto a tampa abre',async()=>{const h=setupV3(),s=h.scene(h.context.ACTIVITIES[18]),e=s.runState.entities.find(e=>e.type==='chest');s.testMode=false;let config;s.tweens={add(c){config=c;}};s.entitySprites=new Map([[e.id,{image:{setTexture(){}}}]]);const pending=h.context.AnimationSystem.transition(s,e,'closed','open');assert.equal(e.state,'opening');assert.equal(h.context.DungeonSystem.isBlocked(s,e.row,e.column).cause,'CLOSED_DOOR_BLOCK');config.onComplete();await pending;assert.equal(h.context.DungeonSystem.isBlocked(s,e.row,e.column),null);});
test('V3 portas, placas, baús, alavancas, runas, pontes, portais e espinhos têm aparências distintas por estado',()=>{const h=setupV3();h.load('systems/MapRenderer.js');for(const [type,off,on]of [['door','closed','open'],['gate','closed','open'],['pressure_plate','off','on'],['toggle_plate','off','on'],['chest','closed','open'],['lever','off','on'],['light_switch','off','on'],['output_rune','off','correct'],['bridge','inactive','active'],['bridge_segment','inactive','active'],['mirror','inactive','active'],['portal','available','active'],['hazard','retracted','active']]){const shape=state=>h.context.MapRenderer.appearance({id:'object',type,skin:'v3',state});assert.notDeepEqual(shape(off),shape(on),type);}});
test('V3 caixa de pistas permanece oculta até interagir, mesmo após revelar a sala',()=>{const h=fixture({v3:true}),s=h.game(6);h.context.DiscoverySystem.reveal(s,['biblioteca']);assert.equal(h.host.querySelector('.clue-dialog').hidden,true);assert.ok(!h.host.textContent.includes('CORAGEM'));assert.ok(s.discoveryState.knownObjects.memoria);assert.equal(Object.keys(s.discoveryState.inscriptions).length,0);});
test('V3 portal energiza na origem antes do transporte e finaliza na posição lógica',async()=>{const h=setupV3(),s=h.scene(h.context.ACTIVITIES[8]),e=h.context.DungeonSystem.getEntity(s,'mirror5');s.runState.flags.mirrorReady=true;s.discoveryState.inscriptions.primeira={};s.discoveryState.inscriptions.segunda={};s.gutoPosition={linha:e.row,coluna:e.column};const order=[];h.context.AnimationSystem.transition=async(scene,entity,from,to)=>{order.push('energia');assert.deepEqual({...scene.gutoPosition},{linha:e.row,coluna:e.column});entity.state=to;};h.context.AnimationSystem.teleport=async(scene,action)=>{order.push('entrada');action();order.push('saida');};await h.context.DungeonSystem.callApi(s,'entrar_espelho',[5]);assert.deepEqual(order,['energia','entrada','saida']);assert.deepEqual({...s.gutoPosition},{linha:e.target.row,coluna:e.target.column});});
test('V3 família de placas: sequência configurável reage à ordem e reinicia com a tentativa',()=>{const h=setupV3(),a={...h.context.ACTIVITIES[0],mapa:[[1,1,1,1]],startPosition:{linha:0,coluna:0},regions:[],entities:[{id:'first',type:'toggle_plate',mode:'sequence',sequenceGroup:'runa',sequenceIndex:0,row:0,column:1},{id:'second',type:'toggle_plate',mode:'sequence',sequenceGroup:'runa',sequenceIndex:1,row:0,column:2},{id:'gate',type:'gate',row:0,column:3,requires:['sequence_runa']}]},s=h.scene(a),enter=col=>{s.gutoPosition={linha:0,coluna:col};h.context.DungeonSystem.onEnter(s,0,col);};enter(2);assert.equal(s.runState.flags.sequence_runa,false);enter(1);assert.equal(s.runState.sequences.runa,1);enter(2);assert.equal(s.runState.flags.sequence_runa,true);assert.equal(h.context.MechanismSystem.requirements(s,s.runState.entities[2]),true);h.context.DungeonSystem.resetRun(s);assert.equal(s.runState.sequences.runa,undefined);assert.equal(s.runState.entities[0].state,'off');});
