// Additive authoring pass: geometry and official programs come unchanged from V3.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {setupV3}=require('../../tests/v3-helpers.cjs');
const root=path.resolve(__dirname,'../..');
const budgets=[18,22,26,28,38,20,26,34,38,56,24,28,36,40,65,20,26,28,30,72];
const pos=e=>`${e.row},${e.column}`,distance=(a,b)=>Math.abs(a.row-b.row)+Math.abs(a.column-b.column);
function reachable(s) {
 const seen=new Set(),queue=[[s.startPosition.linha,s.startPosition.coluna]];
 while(queue.length){const [row,column]=queue.shift(),key=`${row},${column}`;if(seen.has(key))continue;seen.add(key);
  for(const [r,c] of [[row+1,column],[row-1,column],[row,column+1],[row,column-1]]){
   if(!s.mapa[r]?.[c]||s.mapa[r][c]===4)continue;
   if(s.runState.entities.some(e=>e.row===r&&e.column===c&&e.type==='hazard'&&e.state==='active'))continue;
   if(!seen.has(`${r},${c}`))queue.push([r,c]);
  }
  for(const e of s.runState.entities)if(e.row===row&&e.column===column&&e.target&&e.correct!==false)queue.push([e.target.row,e.target.column]);
 }return seen;
}
(async()=>{
 const h=setupV3(),additions=[];
 for(const a of h.context.ACTIVITIES){
  const trace=[],enter=h.context.DungeonSystem.onEnter;
  h.context.DungeonSystem.onEnter=function(s,row,column){trace.push({row,column});return enter.call(this,s,row,column);};
  const {scene,result}=await h.run(a);h.context.DungeonSystem.onEnter=enter;assert.equal(result.cause,'SUCCESS');
  const reached=reachable(scene),visited=new Set(trace.map(pos));
  const optional=a.entities.filter(e=>e.type==='coin'&&!e.manualCollect),occupied=new Set(a.entities.filter(e=>!optional.includes(e)).map(pos));
  occupied.add(`${a.startPosition.linha},${a.startPosition.coluna}`);
  const candidates=[];
  for(let row=0;row<a.mapa.length;row++)for(let column=0;column<a.mapa[row].length;column++){
   const cell={row,column};if(a.mapa[row][column]!==1||occupied.has(pos(cell))||!reached.has(pos(cell)))continue;
   // Never place currency on a danger or one of the mechanisms' functional tiles.
   candidates.push(cell);
  }
  const chosen=[];
  function choose(pool,score){const next=pool.filter(p=>!chosen.some(c=>pos(c)===pos(p))).sort((x,y)=>score(y)-score(x)||x.row-y.row||x.column-y.column)[0];if(next)chosen.push(next);}
  const spread=p=>chosen.length?Math.min(...chosen.map(c=>distance(c,p))):0;
  const route=candidates.filter(p=>visited.has(pos(p)));
  // Two pickups on the natural route; three encourage voluntary exploration.
  for(const fraction of [.25,.7]){const target=trace[Math.floor((trace.length-1)*fraction)];choose(route,p=>-distance(p,target)+spread(p)*.15);}
  for(const e of optional)if(chosen.length<5&&candidates.some(p=>pos(p)===pos(e)))choose([e],()=>1);
  const detours=candidates.filter(p=>!visited.has(pos(p)));
  while(chosen.length<5){const before=chosen.length;choose(detours.length>=3?detours:candidates,p=>spread(p)*2-Math.min(...trace.map(t=>distance(t,p))));assert.ok(chosen.length>before,`A${a.id}: cinco posições seguras`);}
  const coins=chosen.map((p,i)=>({id:`A${String(a.id).padStart(2,'0')}_C0${i+1}`,type:'coin',row:p.row,column:p.column,skin:'v3',family:'coin',persistent:true}));
  const decorations=[],themes=[['banner_blue_plain','painting_landscape','shield_blue'],['painting_castle','bookshelf_left','banner_blue_gold'],['shield_gold','weapons_crossed_steel','banner_blue_plain'],['banner_blue_gold','painting_castle','weapons_crossed_gold']];
  const theme=themes[a.unidade-1];
  for(const region of a.regions){
   const choices=[];
   for(let c=region.column;c<region.column+region.width;c++){
    const r=region.row-1;
    if(a.mapa[r]?.[c]!==0||!a.mapa[r+1]?.[c]||a.mapa[r+1][c]===4||c%5===2)continue;
    if(decorations.some(d=>distance(d,{row:r,column:c})<3))continue;
    choices.push({row:r,column:c});
   }
   if(choices.length){const cell=choices[Math.floor(choices.length/2)];decorations.push({...cell,id:`decor_${decorations.length+1}`,role:theme[decorations.length%theme.length],size:.7,solid:false});}
  }
  // Decorative shelves live on already solid wall cells; never change collision.
  const shelf=decorations.find(d=>d.role==='bookshelf_left');if(shelf)shelf.label='Estante decorativa';
  additions.push({id:a.id,instructionBudget:budgets[a.id-1],coins,decorations,bookshelves:a.entities.filter(e=>e.type==='inscription'&&a.unidade===2).map(e=>e.id)});
 }
 const output=`// V4 additions only. Generated by node tools/v4/build.cjs; V3 remains the source of maps and programs.\n(function () {\n    'use strict';\n    const additions = ${JSON.stringify(additions,null,2)};\n    for (const config of additions) {\n        const activity = window.ACTIVITIES[config.id - 1];\n        activity.v4 = true;\n        activity.instructionBudget = config.instructionBudget;\n        if (!activity.objectives.some(o => o.type === 'budget')) activity.objectives.push({type:'budget',label:'Respeite o orçamento de instruções'});\n        activity.entities = activity.entities.filter(e => e.type !== 'coin' || e.manualCollect).map(e => ({ ...e, ...(e.type === 'coin' && e.manualCollect ? {type:'ruby',family:'ruby',initialState:'available'} : {}), ...(e.type === 'totem' ? {visualVariant:'v4_totem'} : {}), ...(config.bookshelves.includes(e.id) ? {visualVariant:'bookshelf'} : {}) })).concat(config.coins);\n        activity.decorations = config.decorations;\n    }\n})();\n`;
 fs.writeFileSync(path.join(root,'activities-v4.js'),output);
 console.log(`V4: ${additions.length} atividades, ${additions.reduce((n,a)=>n+a.coins.length,0)} moedas, ${additions.reduce((n,a)=>n+a.decorations.length,0)} decorações; mapas e soluções preservados.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
