// Reference documentation only. Never modifies the historical V3 catalog/docs.
const fs=require('node:fs'),path=require('node:path');
const {setupV4}=require('../../tests/v4-helpers.cjs');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'docs/v4'),h=setupV4();fs.mkdirSync(out,{recursive:true});
let answer=fs.readFileSync(path.join(root,'Gabarito_Oficial_Pyton_Knight_V3.txt'),'utf8');
answer=answer.replace('GABARITO OFICIAL V3\n16/09/2026','GABARITO OFICIAL V4\n17/09/2026')
 .replace('Serve exclusivamente à versão que carrega activities-v3.js. O gabarito anterior está preservado em docs/v3/historico.','Usar com activities.js + activities-v3.js + activities-v4.js. Os 20 programas abaixo são os mesmos da V3, sem alteração de percursos ou conceitos. Gabarito V3 preservado na raiz e na release correspondente.')
 .replace('EXECUTAR reinicia posição, mecanismos e inventário provisório; preserva as pistas já descobertas e a luz revelada. REINICIAR limpa a descoberta.','EXECUTAR reinicia posição, mecanismos, chaves e rubis provisórios; preserva pistas e luz revelada. REINICIAR limpa a descoberta.\nAs cinco moedas únicas de cada atividade são opcionais e persistem em todas as reinicializações e replays. Os percursos oficiais não procuram todas as moedas.\nOrçamento V4: qualquer programa válido pode executar acima do limite para explorar. A conclusão exige todos os objetivos e contagem semântica dentro do limite; não é contagem de linhas.\nTentativa: execução válida que inicia a simulação. Parsing/validação estática recusados não contam. TENTAR NOVAMENTE, no modal, começa nova partida com 3 vidas e zero tentativas, preservando código e recompensas salvas.');
let id=0;answer=answer.replace(/Orçamento: [^\n]+/g,()=>{const a=h.context.ACTIVITIES[id++];return `Orçamento semântico: ${a.instructionBudget} | Solução oficial: ${h.context.PythonSubsetParser.parse(a.officialSolution).analysis.instructionCount} instruções`;});
if(id!==20)throw Error('Gabarito precisa ter 20 atividades.');
for(const name of ['Gabarito_Oficial_Pyton_Knight_V4.txt','Gabarito_Final_Pyton_Knight_20_Atividades.txt'])fs.writeFileSync(path.join(root,name),answer);
let matrix='# Matriz de alterações por atividade — V4\n\n17/09/2026. As geometrias, regiões, requisitos, pistas, variantes e soluções permanecem iguais à [matriz V3](../v3/MATRIZ_ATIVIDADES.md). Coordenadas linha/coluna em base zero. As moedas são opcionais; não substituem rubis ou chaves.\n\n| Atividade | Conceito | Solução / limite semântico | Moedas C01 a C05 (linha,coluna) | Decorações | Estantes investigáveis |\n|---|---|---|---|---|---|\n';
for(const a of h.context.ACTIVITIES){const used=h.context.PythonSubsetParser.parse(a.officialSolution).analysis.instructionCount,coins=a.entities.filter(e=>e.type==='coin');matrix+=`| ${a.id}. ${a.nome} | ${a.concept.replaceAll('|','/')} | ${used} / ${a.instructionBudget} | ${coins.map(e=>`(${e.row},${e.column})`).join('; ')} | ${a.decorations.length} | ${a.entities.filter(e=>e.visualVariant==='bookshelf').map(e=>e.id).join(', ')||'—'} |\n`;}
matrix+='\n## Regras comuns\n\n- Duas moedas seguem o percurso natural; pelo menos duas exigem desvios em cada variante. Cinco IDs permanentes por atividade, de A01_C01 a A20_C05.\n- 125 decorações sobre células de parede já existentes; nenhuma nova colisão nas atividades de produção. Paredes e tileset estrutural preservados.\n- As inscrições existentes da Unidade 2 recebem apresentação de estante. Mesmas posições, IDs, textos e requisitos de examinar().\n- Indicador ! em todas as inscrições examináveis, apenas visível a até um tile ortogonal e antes da leitura. Sem indicador em estantes decorativas.\n- Totens das A16 e A20: mesmos IDs e conexões, novos sprites OFF/ON.\n- Limites crescem dentro de cada unidade. A Unidade 4 volta a limites menores para valorizar a compactação por laços, sem alterar os programas oficiais.\n- Tentativas esperadas para aprendizagem continuam as estimativas V3. O modal registra execuções reais, não essas estimativas.\n\n## Evidências\n\n[Acesso às moedas nos 29 cenários](evidencias/auditoria-moedas.json) · [Pistas, portas e dependências](evidencias/auditoria.json) · [Plantas das quatro unidades](evidencias/visual/)\n';
fs.writeFileSync(path.join(out,'MATRIZ_V4.md'),matrix);
fs.writeFileSync(path.join(out,'CATALOGO_ADICOES_V4.json'),JSON.stringify(h.context.ACTIVITIES.map(a=>({id:a.id,name:a.nome,instructionBudget:a.instructionBudget,semanticInstructions:h.context.PythonSubsetParser.parse(a.officialSolution).analysis.instructionCount,coins:a.entities.filter(e=>e.type==='coin'),decorations:a.decorations,bookshelves:a.entities.filter(e=>e.visualVariant==='bookshelf').map(e=>e.id),totems:a.entities.filter(e=>e.visualVariant==='v4_totem').map(e=>e.id)})),null,2)+'\n');
console.log('Gabarito V4, matriz e catálogo de adições atualizados; documentação V3 preservada.');
