// Generates V3 reference documents from the exact catalog consumed by the browser.
const fs=require('fs'),path=require('path');const {setupV3}=require('../../tests/v3-helpers.cjs');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'docs/v3'),h=setupV3(),activities=h.context.ACTIVITIES;
const audit=JSON.parse(fs.readFileSync(path.join(out,'evidencias/auditoria.json')));
const write=(name,text)=>fs.writeFileSync(path.join(out,name),text+'\n');
const escape=s=>String(s??'').replaceAll('|','\\|').replaceAll('\n',' ');
const names={inscription:'inscrição',light_switch:'interruptor de luz',lever:'alavanca',gate:'grade/cofre',door:'porta',guardian:'guardião',hazard:'espinhos',key:'chave',coin:'coletável',output_rune:'runa de saída',pedestal:'pedestal de entrada',bridge:'ponte retrátil',bridge_segment:'segmento de ponte',totem:'totem',mirror:'espelho',portal:'portal',chest:'baú',toggle_plate:'placa alternadora/lógica',pressure_plate:'placa de pressão'};
const mandatory={1:'Câmara da luz; retorno à passagem central.',2:'Ala da alavanca e retorno ao salão.',3:'Os dois arquivos, em lados opostos.',4:'Sala da lâmpada; oficina de segurança OU passarela de inspeção.',5:'Alas da orientação, mudança e cálculo.',6:'Arquivo antigo e galeria da voz.',7:'Biblioteca, pedestal, guardião e porta.',8:'Duas oficinas e a ponte construída.',9:'Os dois arquivos, mesa dos espelhos e destino do cofre.',10:'Arquivos A, B e C; ponte e espelho de retorno; três selos iluminados.',11:'Ala remota da chave e retorno aos bloqueios.',12:'Bifurcação e galeria segura conforme estado da placa.',13:'Arquivo da energia, arquivo da medida e validadores.',14:'Ala azul, ala verde e placa de segurança; portões OU e E.',15:'Arquivos do Sol, Lua e Sombra; chave, alavanca e destino do ramo correto.',16:'Galeria dos totens, retorno e ponte de cinco segmentos.',17:'Os cinco nichos de rubis e porta do contador.',18:'Três, quatro ou cinco módulos ativos conforme cenário; retorno convergente.',19:'Criptas pesquisadas até a chave; retorno à porta. O prefixo visitado varia.',20:'Galeria das runas, ala de espinhos, busca da chave, três rubis e julgamento.'};
const optional={2:['tesouro'],4:['mecanismo','detour'],5:['reliquia'],9:['falso_a','falso_b'],16:['inscricao']};
function role(a,r){const es=a.entities.filter(e=>h.context.DiscoverySystem.contains(r,e.row,e.column));
 if(r.id==='entrada')return 'Partida e orientação antes da primeira decisão.';
 if(r.id==='final')return 'Cristal/recompensa, acessível após os requisitos físicos.';
 if(r.id.startsWith('halo'))return 'Selo visual do salão: ilumina ao investigar a ala correspondente; não exige pisar em cada casa.';
 if(r.id.startsWith('destino_'))return 'Destino físico de um ramo do julgamento, convergindo à saída.';
 if(r.id==='detour')return 'Alternativa longa que evita o mecanismo de espinhos e registra a inspeção.';
 if(a.id===12&&['upper','lower'].includes(r.id))return 'Alternativa física do if/else; o estado do sensor determina a segurança da travessia.';
 if(es.length)return es.map(e=>`${names[e.type]||e.type}: ${e.id}`).join('; ');
 return 'Bifurcação, acesso ou retorno entre regiões funcionais; sem sala de enchimento isolada.';
}
function variantText(a){if(a.testScenarios)return a.testScenarios.map(s=>`${s.variant}: ${s.label||'cenário'}${s.inputs?` (entradas ${s.inputs.join(', ')})`:''}`).join('; ');if(a.chestKeyVariants)return a.chestKeyVariants.map((id,i)=>`${i}: chave em ${id}`).join('; ');if(a.variantStates)return '0: placa ON/superior segura; 1: placa OFF/inferior segura';return 'Cenário único';}
let answer='PYTON KNIGHT — GABARITO OFICIAL V3\n16/09/2026\n\nUso do avaliador: este arquivo contém soluções e respostas; não faz parte das pistas iniciais do jogo.\nServe exclusivamente à versão que carrega activities-v3.js. O gabarito anterior está preservado em docs/v3/historico.\n\nEXECUTAR reinicia posição, mecanismos e inventário provisório; preserva as pistas já descobertas e a luz revelada. REINICIAR limpa a descoberta.\nNas atividades 1, 6, 11 e 16, avance pelas microetapas VER, EXECUTAR e COMPLETAR; use a solução integral na etapa ESCREVER. Na atividade 6, preencha a palavra somente depois da leitura no Diário.\nO código abaixo é aceito pelo parser/interpreter real. Nenhuma fase usa WASD.\nAtividades 15, 18, 19 e 20 têm três variantes; 12 tem duas. O mesmo algoritmo cobre as variantes.\nAs estimativas de tentativas são metas de design, não medições de alunos nem exigências do runtime.\n';
let matrix='# Matriz das 20 atividades — V3\n\nGerada a partir de `activities-v3.js`, em 16/09/2026. Coordenadas são linha/coluna, base zero. As plantas são revisões estáticas com regiões reveladas, não screenshots do navegador.\n\nAs salas pequenas de partida, bifurcação, retorno e saída têm função de navegação verificável. Alas opcionais são identificadas; não é necessário visitar todos os tiles de uma região. Tentativas são estimativas pedagógicas, não resultados de playtest.\n\n';
let auditMD='# Auditoria anti-atalho e respostas expostas — V3\n\nExecutada sobre as 20 atividades e 29 cenários atuais, pelo mesmo interpretador do jogo. Resultado: PASS nas verificações automatizadas descritas abaixo; homologação visual real permanece pendente.\n\n## Método e limites\n\n- Busca em largura da posição inicial: cristal inacessível com mecanismos fechados e perigos ativos.\n- Busca com requisitos satisfeitos e portais válidos: saída alcançável.\n- Fechamento isolado de cada porta/grade/guardião, mantendo os demais abertos: sem contorno até o cristal, inclusive usando destinos de portais.\n- Omissão individual de cada inscrição obrigatória durante o programa oficial: a atividade não conclui.\n- Remoção isolada de chave, flags, dados, contadores e pistas de portas já resolvidas: mecanismo recusa abertura.\n- Inspeção das plantas das quatro unidades: bifurcações, salas, perigos, objetos, retornos e alternativas.\n- Testes adversariais: print literal sem origem nos inputs, leitura remota, portal incorreto, poder incompatível com variante, laço decorativo, ativação direta da ponte e abertura durante animação.\n\nA auditoria contém '+audit.isolatedMutations+' omissões/requisitos isolados. Não é uma prova formal de todos os programas Python possíveis; alternativas corretas são permitidas. Não exige múltiplas execuções quando o aluno já conhece a solução.\n\n## Resultado por atividade\n\n| Ativ. | Exploração e dependência física | Variantes | Saída inicial | Omissões/requisitos |\n|---|---|---|---|---|\n';
for(const a of activities){const r=audit.report.find(x=>x.activity===a.id);
 answer+=`\n${'='.repeat(62)}\nATIVIDADE ${a.id} — ${a.nome}\nUNIDADE ${a.unidade} | ${a.concept}\n\nObjetivo: ${a.descricao}\nExploração: ${mandatory[a.id]}\nCenários: ${variantText(a)}\nEntradas na ordem: ${a.testInputs?.length?a.testInputs.join(' → '):'nenhuma'}\nOrçamento: ${a.instructionBudget||'sem limite específico de atividade'}\n\n${a.officialSolution}\n\nResultado esperado: SUCCESS, cristal alcançado, objetivos físicos e pedagógicos completos.\n`;
 matrix+=`## ${a.id}. ${a.nome}\n\n| Campo | Definição |\n|---|---|\n| Unidade / dificuldade | ${a.unidade} / ${['tutorial','fácil','média','média-difícil','boss'][(a.id-1)%5]} |\n| Objetivo | ${escape(a.descricao)} |\n| Python | ${escape(a.concept)}; whitelist: ${escape(['variables','strings','booleans','arithmetic',...a.allowedConcepts].join(', '))} |\n| Mapa | ${a.mapDesign.dimensions}; início (${a.startPosition.linha}, ${a.startPosition.coluna}), Leste |\n| Regiões obrigatórias | ${escape(mandatory[a.id])} |\n| Estrutura | ${escape(a.design)} |\n| Mecânicas | ${escape([...new Set(a.entities.map(e=>names[e.type]))].join(', '))} |\n| Variantes | ${escape(variantText(a))} |\n| Tentativas esperadas | ${a.attempts}; estimativa, sem forçar repetição |\n| Orçamento | ${a.instructionBudget||'Sem limite específico; guardas globais continuam ativos'} |\n\n![Planta da atividade ${a.id}](evidencias/visual/atividade-${String(a.id).padStart(2,'0')}.png)\n\n### Regiões e propósito\n\n| Região | Posição e tamanho | Luz inicial | Função |\n|---|---|---|---|\n`;
 for(const reg of a.regions)matrix+=`| ${escape(reg.label)} (${reg.id}) | ${reg.row},${reg.column}; ${reg.width}×${reg.height} | ${reg.lightState} | ${escape(role(a,reg))}${optional[a.id]?.includes(reg.id)?' — alternativa/opcional':''} |\n`;
 matrix+='\n### Pistas e dependências\n\n';
 const clues=a.entities.filter(e=>e.type==='inscription');matrix+=clues.length?clues.map(e=>`- **${e.id}**, (${e.row},${e.column}): ${e.variantTexts?e.variantTexts.join(' / '):e.text}`).join('\n'):'Sem resposta textual secreta; investigação por geometria e estados físicos.';
 const locks=a.entities.filter(e=>e.requires||e.requiresAny||e.requiresClues||e.requiresKey||e.minRubies||e.minTraps||e.minRunes||e.condition||e.variantMinTraps);
 matrix+='\n\n'+locks.map(e=>`- **${e.id}**: \`${JSON.stringify(Object.fromEntries(Object.entries(e).filter(([k])=>k.startsWith('requires')||k.startsWith('min')||['condition','variantMinTraps'].includes(k))))}\``).join('\n');
 matrix+='\n\nObjetivos verificados: '+a.objectives.map(o=>o.label).join('; ')+'.\n\nSolução integral no gabarito da raiz. Estado detalhado e evidências em `evidencias/auditoria.json`.\n\n';
 auditMD+=`| ${a.id} | ${escape(mandatory[a.id])} | ${r.scenarios.length} | Bloqueada | ${r.omissions.length+r.missingRequirements.length} |\n`;
}
fs.writeFileSync(path.join(root,'Gabarito_Final_Pyton_Knight_20_Atividades.txt'),answer);fs.writeFileSync(path.join(root,'Gabarito_Oficial_Pyton_Knight_V3.txt'),answer);
write('MATRIZ_ATIVIDADES.md',matrix);
auditMD+='\n## Respostas de input e descoberta\n\nAtividades 7–10, 13 e 15 recebem entradas. A 6 introduz print e esconde a palavra até a leitura. Inspeção do catálogo, guia, editor inicial, tutoriais e DOM adaptado: nenhuma resposta secreta é pré-preenchida ou publicada em objetivo, legenda ou ajuda de input. O campo abre vazio. O Diário só registra textos examinados. Uma sala iluminada torna os objetos visíveis, mas não lê seu texto automaticamente.\n\nValores de portais identificam destinos; não substituem a investigação dos operandos. A mensagem de erro de um ramo da Atividade 15 pode explicar sua classificação somente após as pistas obrigatórias e a entrada válida. Os testes usam respostas fora da interface; o gabarito é material do avaliador.\n\n## Rotas e objetos opcionais permitidos\n\n- A2: nicho de moeda; A5: nicho de memória/moeda.\n- A4: oficina ou passarela são alternativas legítimas, ambas após iluminação.\n- A9: espelhos falsos são opções do enigma e não concedem transporte/recompensa.\n- A12: apenas a galeria segura da variante é obrigatória.\n- A15: apenas o destino do ramo correto deve ser percorrido, após os três arquivos.\n- A16: inscrição complementar opcional; A17: lore e moeda extra opcionais.\n- A18: os módulos além do comprimento ativo da variante não são exigidos.\n- A19/20: busca encerra no baú da chave; os baús posteriores não são exigidos.\n- A10: selos do salão precisam acender; pisar em cada quadrado de luz não é requisito.\n\nNão foi identificada sala isolada de enchimento. Os espaços sem objetos próprios são partida, circulação, convergência, iluminação de selo ou saída; a matriz registra suas funções.\n\n## Correções da auditoria final\n\nO cofre da Atividade 9 passou a ocupar um gargalo real, sem contorno lateral. Segmentos V3 só são energizados por conexões dos totens; ativar_runa() junto à ponte não contorna a galeria. Objetivos e soluções aprovadas foram preservados.\n';write('AUDITORIA_ANTI_ATALHO.md',auditMD);
write('CATALOGO_ATIVIDADES.json',JSON.stringify(activities,null,2));
console.log('Gabarito, matriz, auditoria e catálogo V3 gerados.');
